In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.backends.mps.is_available())
print(torch.backends.mps.is_built())


1.13.1
True
True


## Scaler

In [2]:
## scaler
scaler = torch.tensor(7.0)
scaler.ndim

0

## Vector

In [3]:
vector = torch.tensor((2,3))
vector

tensor([2, 3])

In [4]:
vector.ndim

1

## MATRIX

In [5]:
MATRIX = torch.tensor([[2,3],[4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [6]:
MATRIX.ndim

2

## TENSOR

In [7]:
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR
TENSOR.ndim

3

In [8]:
TENSOR.shape

torch.Size([1, 3, 3])

In [9]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
TENSOR[0,1]

tensor([4, 5, 6])

In [11]:
TENSOR[0,2,2]

tensor(9)

## Random Tensors

`Random tensors are important to assign random weights to tensors and then adjust the weights`

In [12]:
#Create random tensors
random = torch.rand(3,4)
random

tensor([[0.7799, 0.0519, 0.1381, 0.9221],
        [0.4309, 0.7357, 0.1388, 0.5608],
        [0.8780, 0.7696, 0.1859, 0.7478]])

In [13]:
random.ndim, random.shape

(2, torch.Size([3, 4]))

## ZEROs and ONES

In [14]:
zero = torch.zeros(size= (3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
zero.shape

torch.Size([3, 3])

In [16]:
zero.ndim

2

## Create range of Tensors

In [17]:
range = torch.arange(start=0, end=1000, step=77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [18]:
range.ndim

1

In [19]:
range.shape

torch.Size([13])

## Tensor data type

In [20]:
float_32_tensor = torch.tensor([1.0,2.0],
                              dtype=None,
                              requires_grad=False)
float_32_tensor.dtype

torch.float32

In [21]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [22]:
X = float_32_tensor * float_16_tensor
X

tensor([1., 4.])

In [23]:
X.dtype

torch.float32

### Getting information form tensors
 1. Tensors are not of right datadype
 2. Tensors are not shape
 3. Tensors are not right device

In [24]:
some_tensor = torch.rand((3,4), device='cpu')
some_tensor

tensor([[0.8097, 0.3727, 0.2250, 0.5617],
        [0.1374, 0.5477, 0.7238, 0.0101],
        [0.8997, 0.8300, 0.8380, 0.5044]])

In [25]:
#Find detail about tensors
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.8097, 0.3727, 0.2250, 0.5617],
        [0.1374, 0.5477, 0.7238, 0.0101],
        [0.8997, 0.8300, 0.8380, 0.5044]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


### Manipulating tensors (tensor operations)

* Addidtion
* Substraction
* Multiplication (element wise)
* division
* Matrix Multiplication

In [26]:
tensor = torch.tensor([1,2,3,4])
tensor= tensor +10
tensor

tensor([11, 12, 13, 14])

In [27]:
tensor *10

tensor([110, 120, 130, 140])

In [28]:
tensor -10


tensor([1, 2, 3, 4])

## MATRIX Multiplication
two main ways 
1. Element wise multiplication (Scaler multiplication)
2. Matrix multiplication (Dot product)
    1. Inner dimensions must match
    2. Result will hav ethe shape of outer dimension

In [29]:
print(tensor * tensor)
tensor.dtype

tensor([121, 144, 169, 196])


torch.int64

In [30]:
 res = torch.matmul(tensor, tensor)
tensor.shape
tensor
res

tensor(630)

## Shape Errors while Matrix multiplication

In [31]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[1,2],[3,4],[5,6]])

In [32]:
print(f'tensorA shape', {tensor_A.shape})

tensorA shape {torch.Size([3, 2])}


In [33]:
print(f'tensor_B shape',{tensor_B.shape})

tensor_B shape {torch.Size([3, 2])}


In [34]:
# will error
#X = torch.matmul(tensor_A, tensor_B) 

transpose_B = tensor_B.T
transpose_B.shape


torch.Size([2, 3])

In [35]:
X = torch.matmul(tensor_A, transpose_B)
X

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

### Finding min, max, mean, Sum (Tensor aggregation)

In [36]:
x = torch.arange(10,100,10)
x

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
Y = torch.mean(x.type(torch.float32))
Y

tensor(50.)

In [38]:
x.sum()
sum = torch.sum(x)
sum

tensor(450)

In [39]:
max = torch.max(x)
max

tensor(90)

### Find the positional min and max

In [40]:
min_pos = torch.argmin(x)
min_pos

tensor(0)

In [41]:
max_pos = torch.argmax(x)
max_pos

tensor(8)

### Reshaping stacking, squeezing and unsqueezing tensors

* Reshaping
* Squeeze remove all `1` dimension from a tensor 
* UnSqueeze add a `1` dimension from a tensor 

In [42]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
#change the view
z = x.view(9,1)
z, x


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [45]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

### Squueze

In [46]:

x_reshaped.shape
y= x_reshaped.squeeze()
x_reshaped.shape ,y.shape

(torch.Size([1, 9]), torch.Size([9]))

In [47]:
x_unsquezze = y.unsqueeze(dim=0)
x_unsquezze ,x_unsquezze.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

### torch permute

In [56]:
x_orig = torch.rand( size = (224,224,3))
x_orig.shape
x_permute = x_orig.permute(2,0,1)
x_permute.shape



torch.Size([3, 224, 224])

### numpy and tensors

In [58]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [54]:
tensor = torch.ones(7)
tensor, tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]), torch.float32)

In [60]:
numpy_tensor = tensor.numpy()
numpy_tensor

array([1., 2., 3., 4., 5., 6., 7.])

### Reproducbility in torch
In Short How Neural network learn

`start with some randome numbers  -> tensor operation -> update randome numbers -> again -> again ....`
To reduce the randomness in neural networks use Random seed

In [65]:
import torch

RANDOM_SEED = 42

rt_A = torch.rand(3,4)
rt_B = torch.rand(3,4)
print(rt_A == rt_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [69]:
torch.manual_seed(RANDOM_SEED)
rt_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rt_D = torch.rand(3,4)
print(rt_C == rt_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Runing Tensors and pytorch on GPUs(faster coputation)

   1. Getting a gpu.
   2. Use google colab for free gpu.
   3. Use cloud computing`

In [76]:
import torch
#set the code device agnostic.
device = "cuda" if torch.cuda.is_available() else "cpu"